### ISSUE TITLE
says my gpu is not isolated for passthrough

### ISSUE THREAD

**Issue by Zubbbz** [lexi-src/sGPUpt#16]
PC:
- mobo: Gigabyte B450M DS3H
- cpu: AMD Ryzen 5 5600X
- gpu: NVIDIA RTX 2070 Super

I have IOMMU on in my mobo bios, and enabled in my grub config.
I am using a decently fresh install of endeavouros. I installed qemu-full and virt-manager.
The kernel I am running is 5.15.91-1 LTS

![image](https://user-images.githubusercontent.com/37497090/216884557-29268a38-d039-420c-bef0-6a6977d0847f.png)

Output of lspci:

`00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Starship/Matisse IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:01.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse GPP Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:03.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:03.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse GPP Bridge
00:04.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:05.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:07.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:07.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 61)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse/Vermeer Data Fabric: Device 18h; Function 7
01:00.0 USB controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset USB 3.1 xHCI Compliant Host Controller (rev 01)
01:00.1 SATA controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset SATA Controller (rev 01)
01:00.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Bridge (rev 01)
02:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
02:01.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
02:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
05:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
06:00.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] (rev a1)
06:00.1 Audio device: NVIDIA Corporation TU104 HD Audio Controller (rev a1)
06:00.2 USB controller: NVIDIA Corporation TU104 USB 3.1 Host Controller (rev a1)
06:00.3 Serial bus controller: NVIDIA Corporation TU104 USB Type-C UCSI Controller (rev a1)
07:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Function
08:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Reserved SPP
08:00.1 Encryption controller: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Cryptographic Coprocessor PSPCPP
08:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Matisse USB 3.0 Host Controller
08:00.4 Audio device: Advanced Micro Devices, Inc. [AMD] Starship/Matisse HD Audio Controller
`

**Comment by lexi-src** [comment]
We need to fix the IOMMU detection for GPUs that have more than 2 devices in a group. 

I'll will update you when this issue is fixed.

**Comment by Zubbbz** [comment]
sounds good :+1:

**Comment by Evilkyo** [comment]
For me is [sGPUpt][ERROR] Couldn't find any isolated USB for passthrough!

**Comment by lexi-src** [comment]
I pushed an update that should fix this issue so let me know if it works.

**Comment by Evilkyo** [comment]
> I pushed an update that should fix this issue so let me know if it works.

It's working now. Thanks!

I just had to pass the USB manually after everything installed.

**Comment by RaafatTurki** [comment]
I've had the same issue, so I've just commented out the [relevant line](https://github.com/lexi-src/sGPUpt/blob/3feb5fe608310f6081986d79e023ec55c57ac08f/sGPUpt.sh#L264) and executed the script again (thought it was a miss-detect since I've already done single gpu passthrough on this hardware before).

Now that it finished, it told me to open virtmanager and add my iso then launch the vm, I did all that but no display change. no spice, nothing to see. libvirt says "Graphical console not configured for guest". and now I'm wondering if this is related to this issue.

**Comment by lexi-src** [comment]
> I've had the same issue, so I've just commented out the [relevant line](https://github.com/lexi-src/sGPUpt/blob/3feb5fe608310f6081986d79e023ec55c57ac08f/sGPUpt.sh#L264) and executed the script again (thought it was a miss-detect since I've already done single gpu passthrough on this hardware before).
> 
> Now that it finished, it told me to open virtmanager and add my iso then launch the vm, I did all that but no display change. no spice, nothing to see. libvirt says "Graphical console not configured for guest". and now I'm wondering if this is related to this issue.

Desktop or laptop? and post your IOMMU groups.

**Comment by RaafatTurki** [comment]
@lexi-src I've switched to linux-zen (as it has the acs override patch) and the part relating to this issue resolved itself (my IOMMU groups got cleaner) but I still couldn't see my vm.

**Neofetch:**
```
__os  Arch x86_64
host  H110M-S2PT
kern  6.1.12-zen1-1-zen
_mon  1920x1080 @ 60.00Hz
__wm  herbstluftwm
_cpu  Intel i5-7400
_gpu  NVIDIA GeForce GTX 1050 Ti
_mem  7902MiB
```

**IOMMU groups:**
```
Group 0 - 00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers [8086:591f] (rev 05)
Group 1 - 00:01.0 PCI bridge [0604]: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 05)
Group 2 - 00:14.0 USB controller [0c03]: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller [8086:a12f] (rev 31)
Group 2 - 00:14.0 USB Bus 001 Device 005: ID 0d8c:0017 C-Media Electronics, Inc. RAMPAGE MIRACLE
Group 2 - 00:14.0 USB Bus 001 Device 004: ID 1d57:fa60 Xenta 2.4G Receiver
Group 2 - 00:14.0 USB Bus 001 Device 003: ID 28bd:0905 XP-Pen 10 inch PenTablet
Group 2 - 00:14.0 USB Bus 001 Device 002: ID 0c45:6510 Microdia USB DEVICE
Group 2 - 00:14.0 USB Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Group 2 - 00:14.0 USB Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Group 3 - 00:16.0 Communication controller [0780]: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 [8086:a13a] (rev 31)
Group 4 - 00:17.0 SATA controller [0106]: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] [8086:a102] (rev 31)
Group 5 - 00:1c.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #5 [8086:a114] (rev f1)
Group 6 - 00:1c.5 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #6 [8086:a115] (rev f1)
Group 7 - 00:1c.6 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #7 [8086:a116] (rev f1)
Group 8 - 00:1c.7 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #8 [8086:a117] (rev f1)
Group 9 - 00:1d.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #9 [8086:a118] (rev f1)
Group 10 - 00:1d.1 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #10 [8086:a119] (rev f1)
Group 11 - 00:1f.0 ISA bridge [0601]: Intel Corporation H110 Chipset LPC/eSPI Controller [8086:a143] (rev 31)
Group 11 - 00:1f.2 Memory controller [0580]: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller [8086:a121] (rev 31)
Group 11 - 00:1f.3 Audio device [0403]: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller [8086:a170] (rev 31)
Group 11 - 00:1f.4 SMBus [0c05]: Intel Corporation 100 Series/C230 Series Chipset Family SMBus [8086:a123] (rev 31)
Group 12 - 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] [10de:1c82] (rev a1)
Group 13 - 01:00.1 Audio device [0403]: NVIDIA Corporation GP107GL High Definition Audio Controller [10de:0fb9] (rev a1)
Group 14 - 02:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 0c)
Group 15 - 03:00.0 PCI bridge [0604]: Integrated Technology Express, Inc. IT8892E PCIe to PCI Bridge [1283:8892] (rev 41)
```

**Added kernel params (nothing in `/etc/modprobe.d/`):**
```
intel_iommu=on iommu=pt video=vesafb:off,efifb:off nouveau.modeset=0 rd.driver.pre=vfio-pci pcie_acs_override=downstream,multifunction
```

Notes:
- I always get `Couldn't find any isolated USB for passthrough!` and I always give it a `y`.
- I don't have a display manager, I loging via the tty and launch `startx` in `.profile`

I think this is no longer is related to this issue, feel free to move this to a separate issue.

**Comment by lexi-src** [comment]
> @lexi-src I've switched to linux-zen (as it has the acs override patch) and the part relating to this issue resolved itself (my IOMMU groups got cleaner) but I still couldn't see my vm.
> 
> **Neofetch:**
> 
> ```
> __os  Arch x86_64
> host  H110M-S2PT
> kern  6.1.12-zen1-1-zen
> _mon  1920x1080 @ 60.00Hz
> __wm  herbstluftwm
> _cpu  Intel i5-7400
> _gpu  NVIDIA GeForce GTX 1050 Ti
> _mem  7902MiB
> ```
> 
> **IOMMU groups:**
> 
> ```
> Group 0 - 00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers [8086:591f] (rev 05)
> Group 1 - 00:01.0 PCI bridge [0604]: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 05)
> Group 2 - 00:14.0 USB controller [0c03]: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller [8086:a12f] (rev 31)
> Group 2 - 00:14.0 USB Bus 001 Device 005: ID 0d8c:0017 C-Media Electronics, Inc. RAMPAGE MIRACLE
> Group 2 - 00:14.0 USB Bus 001 Device 004: ID 1d57:fa60 Xenta 2.4G Receiver
> Group 2 - 00:14.0 USB Bus 001 Device 003: ID 28bd:0905 XP-Pen 10 inch PenTablet
> Group 2 - 00:14.0 USB Bus 001 Device 002: ID 0c45:6510 Microdia USB DEVICE
> Group 2 - 00:14.0 USB Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Group 2 - 00:14.0 USB Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Group 3 - 00:16.0 Communication controller [0780]: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 [8086:a13a] (rev 31)
> Group 4 - 00:17.0 SATA controller [0106]: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] [8086:a102] (rev 31)
> Group 5 - 00:1c.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #5 [8086:a114] (rev f1)
> Group 6 - 00:1c.5 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #6 [8086:a115] (rev f1)
> Group 7 - 00:1c.6 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #7 [8086:a116] (rev f1)
> Group 8 - 00:1c.7 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #8 [8086:a117] (rev f1)
> Group 9 - 00:1d.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #9 [8086:a118] (rev f1)
> Group 10 - 00:1d.1 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #10 [8086:a119] (rev f1)
> Group 11 - 00:1f.0 ISA bridge [0601]: Intel Corporation H110 Chipset LPC/eSPI Controller [8086:a143] (rev 31)
> Group 11 - 00:1f.2 Memory controller [0580]: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller [8086:a121] (rev 31)
> Group 11 - 00:1f.3 Audio device [0403]: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller [8086:a170] (rev 31)
> Group 11 - 00:1f.4 SMBus [0c05]: Intel Corporation 100 Series/C230 Series Chipset Family SMBus [8086:a123] (rev 31)
> Group 12 - 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] [10de:1c82] (rev a1)
> Group 13 - 01:00.1 Audio device [0403]: NVIDIA Corporation GP107GL High Definition Audio Controller [10de:0fb9] (rev a1)
> Group 14 - 02:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 0c)
> Group 15 - 03:00.0 PCI bridge [0604]: Integrated Technology Express, Inc. IT8892E PCIe to PCI Bridge [1283:8892] (rev 41)
> ```
> 
> **Added kernel params (nothing in `/etc/modprobe.d/`):**
> 
> ```
> intel_iommu=on iommu=pt video=vesafb:off,efifb:off nouveau.modeset=0 rd.driver.pre=vfio-pci pcie_acs_override=downstream,multifunction
> ```
> 
> Notes:
> 
>     * I always get `Couldn't find any isolated USB for passthrough!` and I always give it a `y`.
> 
>     * I don't have a display manager, I loging via the tty and launch `startx` in `.profile`
> 
> 
> I think this is no longer is related to this issue, feel free to move this to a separate issue.

Provide **/etc/sGPUpt/sGPUpt.log** so I can look into this.

**Comment by lexi-src** [comment]
Closing this since the issue should be resolved now.
