### ISSUE TITLE
[sGPUpt][ERROR] An error occured while creating the VM, report this!

### ISSUE THREAD

**Issue by arcvvolf** [lexi-src/sGPUpt#17]
The script exited with the error in the title. I tried running the script a couple times and it results in the same error.

This is copy from the first run:
#############################################################
#                ♥ sGPUpt made by lexi-src ♥                #
# Report issues @ https://github.com/lexi-src/sGPUpt/issues #
#############################################################
[sGPUpt][INFO] Enter VM name: Windows10Pro
[sGPUpt][INFO] Downloading VirtIO Drivers ISO...
[sGPUpt][INFO] Disabling AppArmor permanently for this distro
[sGPUpt][INFO] Starting QEMU compile... please wait.
[sGPUpt][INFO] Starting EDK2 compile... please wait.
[sGPUpt][INFO] Finished compiling, installing compiled output...
[sGPUpt][INFO] Added user 'redacted' to groups 'libvirt,kvm,input'
[sGPUpt][INFO] Do you want to create a drive named Windows10Pro? [y/N]: y
[sGPUpt][INFO] Size of disk (GB)[default 128]: 128
["VM Configuration"]
{
  "System Type":"Intel"
  "Name":"Windows10Pro"
  "vCPU":"6"
  "Memory":"16384M"
  "Disk":"128G"
  "QEMU Version":"7.2.0"
  "Additional Devices": [ 01:00.0 01:00.1 03:00.0 ]
}
[sGPUpt][ERROR] An error occured while creating the VM, report this!

I searched various forums for issues related to this an have found only a few people mentioning it but all have solutions that involve installing qemu-kvm. 

Here is the log from the final attempt:
[sGPUpt.log](https://github.com/lexi-src/sGPUpt/files/10667424/sGPUpt.log)

The following are some diagnostics I ran from various recommendations on forums relating to other errors{

egrep -c '(vmx|svm)' /proc/cpuinfo
16

kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

LC_ALL=C lscpu | grep Virtualization
Virtualization:                  VT-x

lsmod | grep kvm
kvm_intel             368640  0
kvm                  1028096  1 kvm_intel

virsh
Welcome to virsh, the virtualization interactive terminal.

Type:  'help' for help with commands
       'quit' to quit

virsh # version
Compiled against library: libvirt 8.0.0
Using library: libvirt 8.0.0
Using API: QEMU 8.0.0
error: failed to get the hypervisor version
error: internal error: Cannot find suitable emulator for x86_64

sudo cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.15.0-58-generic root=UUID=a62fee95-a8f9-45d9-8e2d-670afbe29e8e ro intel_iommu=on iommu=pt iommu=1 video=efifb:off quiet splash

--------------------------

Thats the extent of what I can do without help. I have no experience with Linux but 25 years of windows tech support. So not sure if that matters much here but I hope at least some of what I posted helps.

System Specs:
Asrock Z690 PG Riptide
Intel i3 12100F
32Gb DDR-4 3600
Nvidia GTX 1070
Linux Mint 21.1 Cinnamon

**Comment by arcvvolf** [comment]
Well that was simple enough. Seems the script now completes without error:

#############################################################
#                ♥ sGPUpt made by lexi-src ♥                #
# Report issues @ https://github.com/lexi-src/sGPUpt/issues #
#############################################################
[sGPUpt][INFO] Enter VM name: Windows10Pro
[sGPUpt][INFO] Disabling AppArmor permanently for this distro
[sGPUpt][INFO] The drive Windows10Pro already exists. Overwrite it? [y/N]: y
[sGPUpt][INFO] Size of disk (GB)[default 128]: 128
["VM Configuration"]
{
  "System Type":"Intel"
  "Name":"Windows10Pro"
  "vCPU":"6"
  "Memory":"16384M"
  "Disk":"128G"
  "QEMU Version":"7.2.0"
  "Additional Devices": [ 01:00.0 01:00.1 03:00.0 ]
}
[sGPUpt][INFO] Adding additional features/optimizations to Windows10Pro...
[sGPUpt][INFO] Successfully created passthrough hooks!
[sGPUpt][INFO] Finished creating Windows10Pro!
[sGPUpt][INFO] Add your desired OS, then start your VM with Virt Manager or 'sudo virsh start'
[sGPUpt][INFO] A reboot is required for this distro, reboot now? [Y/n]: 

------------------------
Not to get off topic but If I want to change the location of the VM Volume image to a different drive. That is something that can be done without causing problems I assume. Seems like its being stored on the boot drive / linux drive and I have a much larger ssd I'd like to have it on instead.

Thanks for you help, this seems to have resolved my initial problem.

**Comment by lexi-src** [comment]
Remove the comments on these lines:

https://github.com/lexi-src/sGPUpt/blob/cb6ee4a8f538b7c3fbeeba3be494cda55bc5ba49/sGPUpt.sh#L27-L28

**Comment by arcvvolf** [comment]
Something didnt work right I think. Clicking the power on virtual machine button appears to do nothing. If I close the Virtual Machine Manager window and re-open it the QEMU/KVM says connecting but never connects.
Attempting to reboot the computer after that doesnt work it just hangs at a black screen. After about 5 minutes I pressed the reset button. I assume something is hanging in the background. After reboot Virtual Machine Manager window shows QEMU/KVM as connected and displays the VM. I can see its settings but if I press the Power on button it repeats the above.

The system will reboot normally as long as I do not press the Power on button in Virtual Machine Manager. I dont know where to look for a log to even see what happening for this problem. Only place I could think of was /var/log/libvirt/qemu but it just has a .placeholder

Should this be in a new issue or do you want to help in this issue?

**Comment by lexi-src** [comment]
You may need to tweak the hooks a bit to make them work with your OS and hardware.

It could also be vBIOS related but I'm not really sure.

**Comment by arcvvolf** [comment]
Hmmm... is there anything I can provide to help further diagnose the issue? logs, diagnostic commands? I mean I'm not opposed to purging QEMU/KVM and reinstalling it if that would help. Tweak'n the hooks sounds like something that a level 1 noob would have a difficult time with. :)

**Comment by lexi-src** [comment]
I'm sorry but there's not much I can do without dedicating a good amount of time to debugging your system.

If it makes you feel any better you're on the last step of the process so don't lose hope!

**Comment by arcvvolf** [comment]
I see. Well, thank you for your time. Guess suddenly wild Linux appeared and it got me lol.

Might I inquire on the uninstall procedures since this isnt going to work for me.

**Comment by lexi-src** [comment]
I currently don't provide an uninstall script but I may will create one in the future.

For now, run **sudo rm -rf /etc/sGPUpt/** to remove the compile directories then open the script and check for the package you need to remove.

**Comment by arcvvolf** [comment]
Ok, thank you again. Sorry it didnt work out for me but guess thats how it goes some times.
