### ISSUE TITLE
"Failed to compile" when running the script

### ISSUE THREAD

**Issue by halfcyan** [lexi-src/sGPUpt#2]
When running the script, everything works until the EDK2 compile. It says it's starting the compile, then after a while says "Failed to compile? Check the log file." I can't find a log file anywhere, so if you can let me know where that is I'll provide it.
I'm running a Ryzen 5 5600 and Radeon 6600 XT.

**Comment by MBaliver** [comment]
I think it`s sGPUpt.log, mine showed up on the desktop.

**Comment by halfcyan** [comment]
> I think it`s sGPUpt.log, mine showed up on the desktop.

Yep it's there.

[sGPUpt.log](https://github.com/lexi-src/sGPUpt/files/10528952/sGPUpt.log)

**Comment by lexi-src** [comment]
> 
The issue is that you don't have the compiling packages installed.

Which Distro are you using?

**Comment by halfcyan** [comment]
Looks like I didn't have ninja or nasm installed. After installing both (and removing Gnome Boxes because I forgot I had that installed) the script worked.

**Comment by halfcyan** [comment]
The issue I'm having now is that I start the VM and it's just a black screen, but that's probably something I'll have to figure out on my own.

**Comment by lexi-src** [comment]
Is there an error in "/var/log/libvirt/qemu/${YOUR-VM-NAME}.log"?

**Comment by MaxxRK** [comment]
I am also getting this error when trying to install. I have done my best to make sure I have all of the build tools but it seems I am still missing some. Log is attached. I am on fedora 37. Running Ryzen 7 5900x and 6900xt
[sGPUpt.log](https://github.com/lexi-src/sGPUpt/files/10530115/sGPUpt.log)

**Comment by lexi-src** [comment]
> I am also getting this error when trying to install. I have done my best to make sure I have all of the build tools but it seems I am still missing some. Log is attached. I am on fedora 37. Running Ryzen 7 5900x and 6900xt [sGPUpt.log](https://github.com/lexi-src/sGPUpt/files/10530115/sGPUpt.log)

It seems like the script didn't download the packages.

please post the output of **cat /etc/os-release**

**Comment by MaxxRK** [comment]
```
NAME="Nobara Linux"
VERSION="37 (Thirty Seven)"
ID=nobara
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=nobara-logo-icon
CPE_NAME="cpe:/o:nobaraproject:nobara:37"
HOME_URL="https://www.nobaraproject.org/"
DOCUMENTATION_URL="https://www.nobaraproject.org/"
SUPPORT_URL="https://www.nobaraproject.org/"
BUG_REPORT_URL=""
REDHAT_BUGZILLA_PRODUCT="Nobara"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Nobara"
REDHAT_SUPPORT_PRODUCT_VERSION=37
PRIVACY_POLICY_URL=""
VARIANT_ID=workstation

```

**Comment by lexi-src** [comment]
> ```
> NAME="Nobara Linux"
> VERSION="37 (Thirty Seven)"
> ID=nobara
> VERSION_ID=37
> VERSION_CODENAME=""
> PLATFORM_ID="platform:f37"
> PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> ANSI_COLOR="0;38;2;60;110;180"
> LOGO=nobara-logo-icon
> CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> HOME_URL="https://www.nobaraproject.org/"
> DOCUMENTATION_URL="https://www.nobaraproject.org/"
> SUPPORT_URL="https://www.nobaraproject.org/"
> BUG_REPORT_URL=""
> REDHAT_BUGZILLA_PRODUCT="Nobara"
> REDHAT_BUGZILLA_PRODUCT_VERSION=37
> REDHAT_SUPPORT_PRODUCT="Nobara"
> REDHAT_SUPPORT_PRODUCT_VERSION=37
> PRIVACY_POLICY_URL=""
> VARIANT_ID=workstation
> ```
Well the issue is that you used an unsupported OS. 

Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**

**Comment by MaxxRK** [comment]
> > ```
> > NAME="Nobara Linux"
> > VERSION="37 (Thirty Seven)"
> > ID=nobara
> > VERSION_ID=37
> > VERSION_CODENAME=""
> > PLATFORM_ID="platform:f37"
> > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > ANSI_COLOR="0;38;2;60;110;180"
> > LOGO=nobara-logo-icon
> > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > HOME_URL="https://www.nobaraproject.org/"
> > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > SUPPORT_URL="https://www.nobaraproject.org/"
> > BUG_REPORT_URL=""
> > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > REDHAT_SUPPORT_PRODUCT="Nobara"
> > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > PRIVACY_POLICY_URL=""
> > VARIANT_ID=workstation
> > ```
> 
> Well the issue is that you used an unsupported OS.
> 
> Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**

That fixed it right up. Thanks a lot. This script is awesome!

**Comment by lexi-src** [comment]
> > > ```
> > > NAME="Nobara Linux"
> > > VERSION="37 (Thirty Seven)"
> > > ID=nobara
> > > VERSION_ID=37
> > > VERSION_CODENAME=""
> > > PLATFORM_ID="platform:f37"
> > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > ANSI_COLOR="0;38;2;60;110;180"
> > > LOGO=nobara-logo-icon
> > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > HOME_URL="https://www.nobaraproject.org/"
> > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > BUG_REPORT_URL=""
> > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > PRIVACY_POLICY_URL=""
> > > VARIANT_ID=workstation
> > > ```
> > 
> > 
> > Well the issue is that you used an unsupported OS.
> > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> 
> That fixed it right up. Thanks a lot. This script is awesome!

No problem! Does it work well enough to be added to the supported distros list?

**Comment by halfcyan** [comment]
> Is there an error in "/var/log/libvirt/qemu/${YOUR-VM-NAME}.log"?
> 
> I wasn't able to test AMD GPUs so it may or may not work.

There is one: `023-01-29T20:11:06.389888Z qemu-system-x86_64: -device {"driver":"vfio-pci","host":"0000:01:00.0","id":"hostdev2","bus":"pci.4","addr":"0x0"}: vfio 0000:01:00.0: group 13 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
2023-01-29 20:11:06.422+0000: shutting down, reason=failed`

Log is here: [Windows-Gaming.log](https://github.com/lexi-src/sGPUpt/files/10530739/Windows-Gaming.log)

**Comment by halfcyan** [comment]
01:00:0 appears to be my USB controller. There SATA controller and PCI bridge are also on the same IOMMU group I think, which may be what's causing this.

**Comment by halfcyan** [comment]
Removing that allows me to boot but I have no keyboard or mouse. Any way to attach those without using PCIe passthrough? Trying to pass through the USB device results in "unsupported configuration: Can't add host USB device: USB is disabled in this host"

**Comment by MaxxRK** [comment]
> > > > ```
> > > > NAME="Nobara Linux"
> > > > VERSION="37 (Thirty Seven)"
> > > > ID=nobara
> > > > VERSION_ID=37
> > > > VERSION_CODENAME=""
> > > > PLATFORM_ID="platform:f37"
> > > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > > ANSI_COLOR="0;38;2;60;110;180"
> > > > LOGO=nobara-logo-icon
> > > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > > HOME_URL="https://www.nobaraproject.org/"
> > > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > > BUG_REPORT_URL=""
> > > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > > PRIVACY_POLICY_URL=""
> > > > VARIANT_ID=workstation
> > > > ```
> > > 
> > > 
> > > Well the issue is that you used an unsupported OS.
> > > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> > 
> > 
> > That fixed it right up. Thanks a lot. This script is awesome!
> 
> No problem! Does it work well enough to be added to the supported distros list?

I have successfully installed windows. However, when I shut it down it does not revert back to fedora. Screens just go black. Any suggestions? Other than that it seems to work right on this distro. I did go through the script and add the distro name so it would do it in the script. Haven't had the chance to check on a clean install yet though

**Comment by lexi-src** [comment]
> Removing that allows me to boot but I have no keyboard or mouse. Any way to attach those without using PCIe passthrough? Trying to pass through the USB device results in "unsupported configuration: Can't add host USB device: USB is disabled in this host"

Click on "Controller USB 0" in virt-manager then change model to "USB 3"

**Comment by lexi-src** [comment]
> > > > > ```
> > > > > NAME="Nobara Linux"
> > > > > VERSION="37 (Thirty Seven)"
> > > > > ID=nobara
> > > > > VERSION_ID=37
> > > > > VERSION_CODENAME=""
> > > > > PLATFORM_ID="platform:f37"
> > > > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > > > ANSI_COLOR="0;38;2;60;110;180"
> > > > > LOGO=nobara-logo-icon
> > > > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > > > HOME_URL="https://www.nobaraproject.org/"
> > > > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > > > BUG_REPORT_URL=""
> > > > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > > > PRIVACY_POLICY_URL=""
> > > > > VARIANT_ID=workstation
> > > > > ```
> > > > 
> > > > 
> > > > Well the issue is that you used an unsupported OS.
> > > > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> > > 
> > > 
> > > That fixed it right up. Thanks a lot. This script is awesome!
> > 
> > 
> > No problem! Does it work well enough to be added to the supported distros list?
> 
> I have successfully installed windows. However, when I shut it down it does not revert back to fedora. Screens just go black. Any suggestions? Other than that it seems to work right on this distro. I did go through the script and add the distro name so it would do it in the script. Haven't had the chance to check on a clean install yet though

Please reply with the contents of **/etc/libvirt/hooks/qemu.d/Windows-Gaming/release/end/stop.sh**

**Comment by MaxxRK** [comment]
> > > > > > ```
> > > > > > NAME="Nobara Linux"
> > > > > > VERSION="37 (Thirty Seven)"
> > > > > > ID=nobara
> > > > > > VERSION_ID=37
> > > > > > VERSION_CODENAME=""
> > > > > > PLATFORM_ID="platform:f37"
> > > > > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > > > > ANSI_COLOR="0;38;2;60;110;180"
> > > > > > LOGO=nobara-logo-icon
> > > > > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > > > > HOME_URL="https://www.nobaraproject.org/"
> > > > > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > > > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > > > > BUG_REPORT_URL=""
> > > > > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > > > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > > > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > > > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > > > > PRIVACY_POLICY_URL=""
> > > > > > VARIANT_ID=workstation
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Well the issue is that you used an unsupported OS.
> > > > > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> > > > 
> > > > 
> > > > That fixed it right up. Thanks a lot. This script is awesome!
> > > 
> > > 
> > > No problem! Does it work well enough to be added to the supported distros list?
> > 
> > 
> > I have successfully installed windows. However, when I shut it down it does not revert back to fedora. Screens just go black. Any suggestions? Other than that it seems to work right on this distro. I did go through the script and add the distro name so it would do it in the script. Haven't had the chance to check on a clean install yet though
> 
> Please reply with the contents of **/etc/libvirt/hooks/qemu.d/Windows-Gaming/release/end/stop.sh**

`#!/bin/bash
set -x

virsh nodedev-reattach pci_0000_25_00_0
virsh nodedev-reattach pci_0000_25_00_1
virsh nodedev-reattach pci_0000_2a_00_1
virsh nodedev-reattach pci_0000_2a_00_3
virsh nodedev-reattach pci_0000_2e_00_3

systemctl start display-manager

for file in /sys/class/vtconsole/*; do
  if (( $(grep -c "frame buffer" $file/name) == 1 )); then
    echo 1 > $file/bind
  fi
done

systemctl set-property --runtime -- user.slice AllowedCPUs=0-23
systemctl set-property --runtime -- system.slice AllowedCPUs=0-23
systemctl set-property --runtime -- init.scope AllowedCPUs=0-23
`

**Comment by MaxxRK** [comment]
> > > > > > ```
> > > > > > NAME="Nobara Linux"
> > > > > > VERSION="37 (Thirty Seven)"
> > > > > > ID=nobara
> > > > > > VERSION_ID=37
> > > > > > VERSION_CODENAME=""
> > > > > > PLATFORM_ID="platform:f37"
> > > > > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > > > > ANSI_COLOR="0;38;2;60;110;180"
> > > > > > LOGO=nobara-logo-icon
> > > > > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > > > > HOME_URL="https://www.nobaraproject.org/"
> > > > > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > > > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > > > > BUG_REPORT_URL=""
> > > > > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > > > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > > > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > > > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > > > > PRIVACY_POLICY_URL=""
> > > > > > VARIANT_ID=workstation
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Well the issue is that you used an unsupported OS.
> > > > > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> > > > 
> > > > 
> > > > That fixed it right up. Thanks a lot. This script is awesome!
> > > 
> > > 
> > > No problem! Does it work well enough to be added to the supported distros list?
> > 
> > 
> > I have successfully installed windows. However, when I shut it down it does not revert back to fedora. Screens just go black. Any suggestions? Other than that it seems to work right on this distro. I did go through the script and add the distro name so it would do it in the script. Haven't had the chance to check on a clean install yet though
> 
> Please reply with the contents of **/etc/libvirt/hooks/qemu.d/Windows-Gaming/release/end/stop.sh**

```
#!/bin/bash
set -x

virsh nodedev-reattach pci_0000_25_00_0
virsh nodedev-reattach pci_0000_25_00_1
virsh nodedev-reattach pci_0000_2a_00_1
virsh nodedev-reattach pci_0000_2a_00_3
virsh nodedev-reattach pci_0000_2e_00_3

systemctl start display-manager

for file in /sys/class/vtconsole/*; do
  if (( $(grep -c "frame buffer" $file/name) == 1 )); then
    echo 1 > $file/bind
  fi
done

systemctl set-property --runtime -- user.slice AllowedCPUs=0-23
systemctl set-property --runtime -- system.slice AllowedCPUs=0-23
systemctl set-property --runtime -- init.scope AllowedCPUs=0-23

```

**Comment by lexi-src** [comment]
> > > > > > > ```
> > > > > > > NAME="Nobara Linux"
> > > > > > > VERSION="37 (Thirty Seven)"
> > > > > > > ID=nobara
> > > > > > > VERSION_ID=37
> > > > > > > VERSION_CODENAME=""
> > > > > > > PLATFORM_ID="platform:f37"
> > > > > > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > > > > > ANSI_COLOR="0;38;2;60;110;180"
> > > > > > > LOGO=nobara-logo-icon
> > > > > > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > > > > > HOME_URL="https://www.nobaraproject.org/"
> > > > > > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > > > > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > > > > > BUG_REPORT_URL=""
> > > > > > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > > > > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > > > > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > > > > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > > > > > PRIVACY_POLICY_URL=""
> > > > > > > VARIANT_ID=workstation
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Well the issue is that you used an unsupported OS.
> > > > > > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> > > > > 
> > > > > 
> > > > > That fixed it right up. Thanks a lot. This script is awesome!
> > > > 
> > > > 
> > > > No problem! Does it work well enough to be added to the supported distros list?
> > > 
> > > 
> > > I have successfully installed windows. However, when I shut it down it does not revert back to fedora. Screens just go black. Any suggestions? Other than that it seems to work right on this distro. I did go through the script and add the distro name so it would do it in the script. Haven't had the chance to check on a clean install yet though
> > 
> > 
> > Please reply with the contents of **/etc/libvirt/hooks/qemu.d/Windows-Gaming/release/end/stop.sh**
> 
> ```
> #!/bin/bash
> set -x
> 
> virsh nodedev-reattach pci_0000_25_00_0
> virsh nodedev-reattach pci_0000_25_00_1
> virsh nodedev-reattach pci_0000_2a_00_1
> virsh nodedev-reattach pci_0000_2a_00_3
> virsh nodedev-reattach pci_0000_2e_00_3
> 
> systemctl start display-manager
> 
> for file in /sys/class/vtconsole/*; do
>   if (( $(grep -c "frame buffer" $file/name) == 1 )); then
>     echo 1 > $file/bind
>   fi
> done
> 
> systemctl set-property --runtime -- user.slice AllowedCPUs=0-23
> systemctl set-property --runtime -- system.slice AllowedCPUs=0-23
> systemctl set-property --runtime -- init.scope AllowedCPUs=0-23
> ```

Please upload **sGPUpt.log & /var/log/libvirt/qemu/${YOUR-VM-NAME}.log**

**Comment by MaxxRK** [comment]
> > > > > > > > ```
> > > > > > > > NAME="Nobara Linux"
> > > > > > > > VERSION="37 (Thirty Seven)"
> > > > > > > > ID=nobara
> > > > > > > > VERSION_ID=37
> > > > > > > > VERSION_CODENAME=""
> > > > > > > > PLATFORM_ID="platform:f37"
> > > > > > > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > > > > > > ANSI_COLOR="0;38;2;60;110;180"
> > > > > > > > LOGO=nobara-logo-icon
> > > > > > > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > > > > > > HOME_URL="https://www.nobaraproject.org/"
> > > > > > > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > > > > > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > > > > > > BUG_REPORT_URL=""
> > > > > > > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > > > > > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > > > > > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > > > > > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > > > > > > PRIVACY_POLICY_URL=""
> > > > > > > > VARIANT_ID=workstation
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > Well the issue is that you used an unsupported OS.
> > > > > > > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> > > > > > 
> > > > > > 
> > > > > > That fixed it right up. Thanks a lot. This script is awesome!
> > > > > 
> > > > > 
> > > > > No problem! Does it work well enough to be added to the supported distros list?
> > > > 
> > > > 
> > > > I have successfully installed windows. However, when I shut it down it does not revert back to fedora. Screens just go black. Any suggestions? Other than that it seems to work right on this distro. I did go through the script and add the distro name so it would do it in the script. Haven't had the chance to check on a clean install yet though
> > > 
> > > 
> > > Please reply with the contents of **/etc/libvirt/hooks/qemu.d/Windows-Gaming/release/end/stop.sh**
> > 
> > 
> > ```
> > #!/bin/bash
> > set -x
> > 
> > virsh nodedev-reattach pci_0000_25_00_0
> > virsh nodedev-reattach pci_0000_25_00_1
> > virsh nodedev-reattach pci_0000_2a_00_1
> > virsh nodedev-reattach pci_0000_2a_00_3
> > virsh nodedev-reattach pci_0000_2e_00_3
> > 
> > systemctl start display-manager
> > 
> > for file in /sys/class/vtconsole/*; do
> >   if (( $(grep -c "frame buffer" $file/name) == 1 )); then
> >     echo 1 > $file/bind
> >   fi
> > done
> > 
> > systemctl set-property --runtime -- user.slice AllowedCPUs=0-23
> > systemctl set-property --runtime -- system.slice AllowedCPUs=0-23
> > systemctl set-property --runtime -- init.scope AllowedCPUs=0-23
> > ```
> 
> Please upload **sGPUpt.log & /var/log/libvirt/qemu/${YOUR-VM-NAME}.log**

[Windows-Gaming.log](https://github.com/lexi-src/sGPUpt/files/10530951/Windows-Gaming.log)
[sGPUpt.log](https://github.com/lexi-src/sGPUpt/files/10530952/sGPUpt.log)

**Comment by lexi-src** [comment]
> > > > > > > > > ```
> > > > > > > > > NAME="Nobara Linux"
> > > > > > > > > VERSION="37 (Thirty Seven)"
> > > > > > > > > ID=nobara
> > > > > > > > > VERSION_ID=37
> > > > > > > > > VERSION_CODENAME=""
> > > > > > > > > PLATFORM_ID="platform:f37"
> > > > > > > > > PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
> > > > > > > > > ANSI_COLOR="0;38;2;60;110;180"
> > > > > > > > > LOGO=nobara-logo-icon
> > > > > > > > > CPE_NAME="cpe:/o:nobaraproject:nobara:37"
> > > > > > > > > HOME_URL="https://www.nobaraproject.org/"
> > > > > > > > > DOCUMENTATION_URL="https://www.nobaraproject.org/"
> > > > > > > > > SUPPORT_URL="https://www.nobaraproject.org/"
> > > > > > > > > BUG_REPORT_URL=""
> > > > > > > > > REDHAT_BUGZILLA_PRODUCT="Nobara"
> > > > > > > > > REDHAT_BUGZILLA_PRODUCT_VERSION=37
> > > > > > > > > REDHAT_SUPPORT_PRODUCT="Nobara"
> > > > > > > > > REDHAT_SUPPORT_PRODUCT_VERSION=37
> > > > > > > > > PRIVACY_POLICY_URL=""
> > > > > > > > > VARIANT_ID=workstation
> > > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Well the issue is that you used an unsupported OS.
> > > > > > > > Anyways just run this command then you're set: **dnf install -y "qemu-kvm" "virt-manager" "virt-viewer" "virt-install" "libvirt-daemon-config-network" "libvirt-daemon-kvm" "swtpm" "g++" "ninja-build" "nasm" "iasl" "libuuid-devel" "glib2-devel" "pixman-devel" "spice-protocol" "spice-server-devel"**
> > > > > > > 
> > > > > > > 
> > > > > > > That fixed it right up. Thanks a lot. This script is awesome!
> > > > > > 
> > > > > > 
> > > > > > No problem! Does it work well enough to be added to the supported distros list?
> > > > > 
> > > > > 
> > > > > I have successfully installed windows. However, when I shut it down it does not revert back to fedora. Screens just go black. Any suggestions? Other than that it seems to work right on this distro. I did go through the script and add the distro name so it would do it in the script. Haven't had the chance to check on a clean install yet though
> > > > 
> > > > 
> > > > Please reply with the contents of **/etc/libvirt/hooks/qemu.d/Windows-Gaming/release/end/stop.sh**
> > > 
> > > 
> > > ```
> > > #!/bin/bash
> > > set -x
> > > 
> > > virsh nodedev-reattach pci_0000_25_00_0
> > > virsh nodedev-reattach pci_0000_25_00_1
> > > virsh nodedev-reattach pci_0000_2a_00_1
> > > virsh nodedev-reattach pci_0000_2a_00_3
> > > virsh nodedev-reattach pci_0000_2e_00_3
> > > 
> > > systemctl start display-manager
> > > 
> > > for file in /sys/class/vtconsole/*; do
> > >   if (( $(grep -c "frame buffer" $file/name) == 1 )); then
> > >     echo 1 > $file/bind
> > >   fi
> > > done
> > > 
> > > systemctl set-property --runtime -- user.slice AllowedCPUs=0-23
> > > systemctl set-property --runtime -- system.slice AllowedCPUs=0-23
> > > systemctl set-property --runtime -- init.scope AllowedCPUs=0-23
> > > ```
> > 
> > 
> > Please upload **sGPUpt.log & /var/log/libvirt/qemu/${YOUR-VM-NAME}.log**
> 
> [Windows-Gaming.log](https://github.com/lexi-src/sGPUpt/files/10530951/Windows-Gaming.log) [sGPUpt.log](https://github.com/lexi-src/sGPUpt/files/10530952/sGPUpt.log)

You seem to be experiencing the reset bug on AMD GPUs. I recommend that you ask for help on the VFIO subreddit since I have limited experience with AMD cards.
